### ISSUE TITLE
Assign random reviewer from a group

### ISSUE THREAD

**Issue by Borda** [Mergifyio/mergify-engine#1054]
Hello, I am wondering if there is an option instead of assigning (and the spamming whole team with notifications and emails) assigned a reviewer from a list, something like:
```
  - name: add core reviewer
    conditions:
      # number of review approvals
      - "#approved-reviews-by<3"
    actions:
      request_reviews:
        reviewers: 1
        users:
          - Borda
          - abcd12
          - ...
```
