### ISSUE TITLE
Ability to highlight author if a backport PR cannot be created

### ISSUE THREAD

**Issue by leseb** [Mergifyio/mergify-engine#1096]
If Mergify fails to cherry-pick commits and thus to create a backport PR, it would be nice to highlight the author about that.

Really similar to the recent `conflict` action.

Thanks.

**Comment by jd** [comment]
It'd be cool to be able to do something like:

```
- name: notify the author if backport fails
  conditions:
    - label=conflicts
    # Optionally match on the branch name here
  actions:
    comment:
      message: This backport is in conflict @{{backported.author}}
```

That would require Mergify to track the PR it has backported, but that shouldn't be too hard.
