### ISSUE TITLE
Ability to check commit semantic conformity

### ISSUE THREAD

**Issue by leseb** [Mergifyio/mergify-engine#1123]
Before anyone asks, yes I'm aware of the existence of https://github.com/zeke/semantic-pull-requests, so perhaps I can start by explaining why it does not fully work for me:

* it uses https://www.npmjs.com/package/parse-commit-message which is less feature-rich than https://github.com/conventional-changelog/commitlint
* very few contributions over time, it almost seems the project is stale at this point
* many obvious bugs making it un-usable like these 2: https://github.com/zeke/semantic-pull-requests/issues/82 and https://github.com/zeke/semantic-pull-requests/issues/88

Just to be clear it's not a complaint against semantic-pull-requests, these are just facts :-).

With that said, I wish Mergify could rely on https://github.com/conventional-changelog/commitlint to parse each commit of a given PR and output any anomaly as part of the PR check status. To go further, Mergify could attempt to read and pass any commitlint configuration it finds in `.github` (see for reference https://github.com/conventional-changelog/commitlint#config).

So it would be nice to a new action that does:

```
  - name: automatically lint commits
    conditions:
      - base=master
      - label!=work-in-progress
    actions:
      lint_commits: {}
        config: .github/.commitlintrc.yml # optional
```

Hopefully, that makes sense! Feel free to disregard if this is too out of scope :)
Bisous.
