### ISSUE TITLE
Allow to delete head branch even if branch is in use

### ISSUE THREAD

**Issue by thomaseizinger** [Mergifyio/mergify-engine#1176]
GitHub recently implemented the following feature: https://github.blog/changelog/2020-05-19-pull-request-retargeting/

This makes it very easy to submit follow-up PRs for PRs that are still open.

For this to work, the head of the original PR needs to be deleted. We have a rule for this in mergify looking like this:

```yml
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
      - head~=^(?!release.*).*$
    actions:
      delete_head_branch:
```

Unfortunately, it doesn't work in this particular case because:

![image](https://user-images.githubusercontent.com/5486389/84452824-402f3c80-ac9a-11ea-8f58-fad6ce82290b.png)

Any chance we can make it possible for mergify to still delete the head branch in this particular case?

- Maybe provide an option for force delete if you don't want to change the default behaviour?

```yml
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
      - head~=^(?!release.*).*$
    actions:
      delete_head_branch:
        force_if_still_in_use: true
```

- Alternatively, `mergify` could build on top of the new GitHub behaviour and detect that the PR in question is a follow-up PR and the head branch should actually be deleted to trigger the new GitHub behaviour.
