### ISSUE TITLE
'update' action is not documented

### ISSUE THREAD

**Issue by remal** [Mergifyio/mergify-engine#1338]
Hello Mergify maintainers,

I'd like to have a tool that tries to merge base branch to PR branch using merge commit. Yes, for my own reasons I don't like rebases.

I expect the tool to do it automatically, when a new commit is added to base branch. If there is a conflict, I'd like to be notified somehow.

I'm hoping that 'update' Mergify action can do it, but, unfortunately, it's not documented: https://doc.mergify.io/actions.html#update. As you can see, there is a title and short description, but nothing more. Could you please document it? Am I able to achieve my goal y using this action?

PS: I'm not sure if it's the right place to open an issue.

**Comment by jd** [comment]
Hi @remal,

There's actually nothing more to document. If you specify the `update` action with e.g.

```yaml
pull_request_rules:
  - name: update all PR
    conditions:
      - base=master
    actions:
      update:
```

It will update your PR with the latest base branch each time it's not up-to-date.
