### ISSUE TITLE
Fix unchecked status-success 

### ISSUE THREAD

**Issue by MSNTCS** [Mergifyio/mergify-engine#1367]
Greetings!
Thank you for your great repository. 
We have added the mergify bot to our repository and we could manage to successfully run it in some of our PRs, but it seems it is not working in some others despite the fact that every check worked fine in the PR. I checked the summary of mergify and it seems `status-success` remains unchecked while the rest of the conditions were checked.  Under what conditions might this happen? I have checked all of your documents and opened and closed issues but I could not find its reason. I would appreciate it if you could guide me on this matter.
Here is the `mergify.yml`: 
```
pull_request_rules:
  - name: Merge when CI passes and resolves all requested reviews
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "status-success~=^Actions - "
      - status-success=continuous-integration/travis-ci/pr
      - base=master
      - label!=do-not-merge
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: smart
```
Here is the Mergify/Summery:
<img width="573" alt="Screen Shot 2020-09-10 at 10 47 22 AM" src="https://user-images.githubusercontent.com/50092326/92677882-b9a0fe80-f35f-11ea-8db1-8b0e37a636b3.png">
