### ISSUE TITLE
Randomly sample N users from a team when assigning PRs

### ISSUE THREAD

**Issue by ianks** [Mergifyio/mergify-engine#1388]
Our use case is that we want to be able to assign a random team member to a dependabot PR, only when the status checks fail. Currently, this is not possible.

So something like:

```yaml
pull_request_rules:
  - name: Assign team member to  dependabot PR
    conditions:
      - author=dependabot[bot]
      - status-failure=test
    actions:
      assign:
        count: 1
        teams:
          - myteam
```
