### ISSUE TITLE
Extending configurations

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#150]
I think it would be helpful to allow for the ability to _extend_ Mergify configurations.

The use case that I'm experiencing with my team is that we have several different repos that all follow roughly the same merging conditions. In order to add Mergify to each repo, we'd have to add a configuration to each one. If we wanted to tweak a setting, we'd have to make the same change in each repository as well. This could be avoided by having a mechanism for extending configurations.

Here's an example of how this could look (just using this example to illustrate the idea, though there are many different ways this could be done):

In one repository, (let's say github.com/Mergifyio/awesome-project) there could be a "root" Mergify configuration in the `.mergify.yml` file:

```yaml
rules:
  default:
    protection:
      required_status_checks:
        strict: True
        contexts:
          - 'linting'
          - 'tests'
      required_pull_request_reviews:
        required_approving_review_count: 2

    disabling_label: 'no-mergify'
    merge_strategy:
      method: rebase
      rebase_fallback: none
```

In another repository (let's say github.com/Mergifyio/second-project), the Mergify configuration could _extend_ the other configuration. The `.mergify.yml` file for this configuration could look like:

```yaml
rules:
  <<: *github.com/Mergifyio/awesome-project#.mergify.yaml
  required_pull_request_reviews:
    required_approving_review_count: 4
```

Note that this example uses the [YAML anchors syntax](http://yaml.org/spec/1.2/spec.html#id2785586), but modifies it to support references other than in-file anchors. Since the Mergify Bot has access to an entire organization, other GitHub repos in the organization could be easily referenced (even if private), but extending could also support URLs, relative file paths, etc.

**Comment by edahlseng** [comment]
Thinking about this a bit more, I'm not sure that overloading the YAML anchors syntax is the best option here. That would mean that the configuration file would technically be invalid YAML. Instead, I think it would be better to support something similar to the [extends syntax that ESLint uses](https://eslint.org/docs/developer-guide/shareable-configs#using-a-shareable-config). This would ensure that the Mergify configuration is valid YAML. A configuration would then look something like this:

```yaml
extends: github.com/Mergifyio/awesome-project#.mergify.yaml
rules:
  required_pull_request_reviews:
    required_approving_review_count: 4
```

If I submit a PR with the logic for this, would there be support to merge it in?
