### ISSUE TITLE
'update' action not working as expected

### ISSUE THREAD

**Issue by calebmshafer** [Mergifyio/mergify-engine#1595]
The update action sounds like it should do exactly what I'm looking for, however I am having trouble getting it to work. I add the following config:

```
pull_request_rules:
  - name: update all PR
    conditions:
      - "#changes-requested-reviews-by=0"
      - -draft
      - base=master
    actions:
      update:
```

and receive the following error by the Mergify validator;

`expected a dictionary for dictionary value @ data['pull_request_rules'][0]['actions']['update']`

Am I using it incorrectly?

Here is an example [PR](https://github.com/calebmshafer/imodeljs/pull/6).

**Comment by sileht** [comment]
This should work:
```
pull_request_rules:
  - name: update all PR
    conditions:
      - "#changes-requested-reviews-by=0"
      - -draft
      - base=master
    actions:
      update: {}
```
