### ISSUE TITLE
Mysterious race condition bug

### ISSUE THREAD

**Issue by SachinShekhar** [Mergifyio/mergify-engine#1639]
Look at this Pull Request: https://github.com/ServerlesslyStack/Serverlessly/pull/3

`Semantic Pull Request` check is completely failed (which is expected as the repo doesn't recognise `build` type).

Based on this check, I had configured Mergify to add or remove `pr-title-issue` label (which is important condition for merging).

```yaml
    {
      name: Add pr-title-issue label,
      conditions:
        [check-failure=Semantic Pull Request, -closed, label!=pr-title-issue],
      actions: { label: { add: [pr-title-issue] } },
    },
    {
      name: Remove pr-title-issue label,
      conditions: [check-success=Semantic Pull Request, label=pr-title-issue],
      actions: { label: { remove: [pr-title-issue] } },
    },
```

This should add `pr-title-issue` to the Pull Request once. But, this started adding and removing `pr-title-issue` non-stop. It's great that I noticed it quickly and [disabled the rules](https://github.com/ServerlesslyStack/Serverlessly/blob/e167a780c0cb4549db9e7153b678ca0af5890ac9/.github/mergify.yml#L40-L50) after 16 instances of label addition/removal, otherwise it could end up doing it forever.

Interestingly, Mergify dashboard evaluates the config against the PR just fine as expected.

<img width="388" alt="Screenshot 2020-12-11 at 6 03 13 PM" src="https://user-images.githubusercontent.com/6867716/101906290-bb889100-3bde-11eb-95a5-3fbfe0b3bf5a.png">

The above evaluation clearly says that Mergify shouldn't remove the `pr-title-issue` label even after addition of this label. And, yet, it removes the label. This is clearly a bug of the Mergify Engine.
