### ISSUE TITLE
Remove approval after a new patch

### ISSUE THREAD

**Issue by mrunge** [Mergifyio/mergify-engine#1860]
I'm not sure if this is a config issue or a real bug. 

There was
https://github.com/gnocchixyz/gnocchi/pull/1100
which was only a small change, no controversy etc, and it was approved, but CI failed. I pushed another patch, relaxing CI; The approval was still in place and that patch was merged.

The request here is: can approval get removed automatically after pushing a new commit? Otherwise that opens a big door for all kinds of changes; as long as CI passes, you could commit anything.

**Comment by sileht** [comment]
you can use this action: https://docs.mergify.io/actions.html#dismiss-reviews

**Comment by jd** [comment]
Yes, we use something like this for example in this repo:
```yaml
  - name: dismiss reviews except for core devs
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
```

You can set the conditions to `[]` to have it run for every PR in every conditions.
