### ISSUE TITLE
mergify rebase is removing the reviews

### ISSUE THREAD

**Issue by Madhu-1** [Mergifyio/mergify-engine#1942]
```yaml
actions:
      merge:
        method: rebase
        rebase_fallback: merge
        bot_account: ceph-csi-bot
        strict: smart
        strict_method: rebase
      dismiss_reviews: {}
      delete_head_branch: {}
```

we have the above action in our [repo](https://github.com/ceph/ceph-csi/blob/master/.mergify.yml#L41-L49). Recently Mergify started removing the approved reviews when doing rebase, Earlier it was not like that, Mergify used to remove the approvals only if the user pushes his changes. Is it something wrong with our configuration(for a long time) or something recently changed in mergify)
