### ISSUE TITLE
'review' action isn't working

### ISSUE THREAD

**Issue by remal** [Mergifyio/mergify-engine#2000]
I'm using Mergify for my [public repository](https://github.com/remal/tracing-spec/pull/202) and it seems something's been broken in 'review' action lately.

My [Mergify config](https://github.com/remal/tracing-spec/blob/master/.mergify/config.yml) has this rule:
```yaml
pull_request_rules:
- name: Auto approve dependencies
  conditions:
  - author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - label!=dependencies-ci
  - label!=sync-with-template
  - -closed
  - -merged
  actions:
    review: { }
```

PR that should be automatically reviewed by Mergify, but it's not: https://github.com/remal/tracing-spec/pull/202

As I can see from Mergify summary, the conditions for the rule are met, but nothing's happening:
![screen](https://user-images.githubusercontent.com/231188/107210903-d5472880-6a15-11eb-83d0-72d57de1d60e.png)

What am I doing wrong?

**Comment by sileht** [comment]
The default review type is `APPROVE`, GitHub requires a message to be set for `APPROVE`.

I keep this ticket open as this clearly needs to be reported somewhere.

**Comment by remal** [comment]
@sileht I tried to add message like this and it doesn't help:
```yaml
pull_request_rules:
- name: Auto approve dependencies
  conditions:
  - author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - label!=dependencies-ci
  - label!=sync-with-template
  - -closed
  - -merged
  actions:
    review:
      message: 'Approved automatically by @Mergifyio.'
```
