### ISSUE TITLE
Assign the original author to the backported PRs

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#2287]
## What

Enable to assign the original author to the backport action for helping with the tracking.

### Proposal

Extend the `backport` action with a new list option, f.i: `assignees` (or something else), similar to the assign action.

See the below snippet as an example of how to configure mergify with it:

```
pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport-to-stable
    actions:
      backport:
        assignees: ["{{ author }}"]
        branches:
          - stable
```

Thanks
