### ISSUE TITLE
Assign labels to the backported PRs

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#2288]
## What

Enable to add labels to the backport action for helping with the tracking.

### Proposal

Extend the `backport` action with a new list option, f.i: `labels` (or something else)

See the below snippet as an example of how to configure mergify with it:

```
pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport-to-stable
    actions:
      backport:
        labels:
          - "label_1"
          - "label_2"
        branches:
          - stable
```

Thanks
