### ISSUE TITLE
Spaces in status checks

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#233]
It appears that there's an issue with status checks that contain spaces in the name:

```yaml
pull_request_rules:
  - name: default
    conditions:
      - "label≠no-mergify"
      - "#approved-reviews-by>=1"
      - "status-success=ci/circleci: staging_preview"
...
```

I'm getting the following error:
```
Mergify configuration is invalid: extra keys not allowed @ data['pull_request_rules'], Invalid condition 'status-success=ci/circleci: staging_preview'. Expected end of text (at char 28), (line:1, col:29) @ data['pull_request_rules'][0]['conditions'][3]
```

This is especially problematic as all status checks names from CircleCI contain spaces.
