### ISSUE TITLE
Configure the title to the backported PRs

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#2363]
## What

Enable to customise the title in the backported PRs.

### Proposal

Extend the `backport` action with a new option, f.i: `title` (or something else).

See the below snippet as an example of how to configure mergify with it:

```
pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport-to-stable
    actions:
      backport:
        title : "foo bar {{ number }}"
        branches:
          - stable
```

Thanks
