### ISSUE TITLE
Append the original description to the backported and copied PRs

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#2414]
## What

Enable to append the original description in the backported and copioed PRs.

### Proposal

Extend the `backport` action with a new option, f.i: `append_original_description` (or something else).

See the below snippet as an example of how to configure mergify with it:

```
pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport-to-stable
    actions:
      backport:
        append_original_description: True
        branches:
          - stable
```

Thanks
