### ISSUE TITLE
Enable target branch attribute in the template for the title option in the copy/backport actions

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#2419]
## What

Enable the target branch attribute when configuring the PR title option in the copy and backport actions.

## Proposal

Extend the template with the `target` attribute

See the below snippet as an example of how to configure mergify with it:

```
  - name: backport patches to 7.x branch
    conditions:
      - merged
      - base=master
      - label=v7.13.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.x"
        title: "[{{ target }}] {{ title }} (backport #{{ number }})"
```

Then the target attribute will match the branch `7.x`

Thanks
