### ISSUE TITLE
Failed configuration

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#272]
I'm getting an error from the `Mergify – future config checker` when using the following configuration:
```yaml
pull_request_rules:
  - name: default
    conditions:
      - "label≠no-mergify"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      merge:
        method: rebase
        rebase_fallback: none
        strict: smart
      delete_head_branch:
        on: merge
```

The error that I'm currently getting is:
```
Mergify configuration is invalid: extra keys not allowed @ data['pull_request_rules'], extra keys not allowed @ data['pull_request_rules'][0]['actions']['delete_head_branch'][True]
```

As far as I can tell from the documentation, this configuration is correct. Am I missing something, or is this a bug?
