### ISSUE TITLE
Rebase fallback, configuration failing

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#274]
After fixing the configuration based on the updated documentation from #272, I'm getting a different error from the `Mergify – future config checker` when using the following configuration:
```yaml
pull_request_rules:
  - name: default
    conditions:
      - "label≠no-mergify"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      merge:
        method: rebase
        rebase_fallback: none
        strict: smart
      delete_head_branch: true
```

The error that I'm getting now is:
```
Mergify configuration is invalid: extra keys not allowed @ data['pull_request_rules'], not a valid value for dictionary value @ data['pull_request_rules'][0]['actions']['merge']['rebase_fallback']
```

As far as I can tell from the documentation, this configuration is also correct. Am I missing something else, or is this a bug?
