### ISSUE TITLE
Implement a "stale" PR thing

### ISSUE THREAD

**Issue by sileht** [Mergifyio/mergify-engine#275]
To do we must create a next data type for date that allow iso date (2018-03-27T14:28:23Z) or  timedelta (5 days)

Then we expose `updated_at`.

And we could write rules like:

```
- name: mark pull request are stale
  conditions:
     - updated_at > 30 days
  actions:
     - label:
          add: stale
- name: close stale pull request
  conditions:
     - updated_at > 60 days
  actions:
     - close: 
         message: The pull request have been stale since 60 days and have been closed automatically.

```
