### ISSUE TITLE
rules with regex not showing up

### ISSUE THREAD

**Issue by renatocaval** [Mergifyio/mergify-engine#303]
I have tried to add a rule like:

```
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
```

But it's not showing up in the checks page nor it's being applied. 

I suspect that this is related with the regex, because I have added a regex to another rule as well and the rule stop to show up after that.
