### ISSUE TITLE
status-success for Azure Pipelines PR validation

### ISSUE THREAD

**Issue by LittleAndi** [Mergifyio/mergify-engine#309]
How do I write a correct status check for the status-success condition when I'm using Azure DevOps Pipelines for pull request validation here on GitHub? I have only seen examples for Travis CI and Circle CI and they look very different. Is this set by GitHub or Azure DevOps?

**Comment by jd** [comment]
Do you have a pull request that we could check to see how it's reported?
How is it different from e.g. Travis?

**Comment by LittleAndi** [comment]
Just like this?

```
pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - status-success="Advent of Code 2018-ASP.NET Core-CI"
      - base=master
    actions:
      merge:
        method: merge
```
