### ISSUE TITLE
Populate labels from the PR to the backported PRs

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#3257]
## What

https://github.com/Mergifyio/mergify-engine/issues/2288 added support for assigning labels to the backported PRs, I'd like to extend this functionality to populate the labels from the source PR to the backported PRs.

### Proposal

Extend the `backport` action with a new list option, f.i: `populate_labels` (or something else)

See the below snippet as an example of how to configure mergify with it:

```
pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=main
      - label=backport-to-stable
    actions:
      backport:
        populate_labels: true
        branches:
          - stable
```

Therefore, given the PR-1 with the labels ['bug', 'customer', 'backport-to-stable' ] then when it gets merged the PR-2 is created with the labels ['bug', 'customer']

Thanks
