### ISSUE TITLE
Mergify merged a PR that didn't yet satisfy all conditions

### ISSUE THREAD

**Issue by monfresh** [Mergifyio/mergify-engine#3288]
## Expected Behavior
Given this Mergify config:
```yaml
queue_rules:
  - name: default
    conditions:
      - "label=ready-to-merge"

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - "label=ready-to-merge"
    actions:
      queue:
        name: default
```

I expect that Mergify would only merge a PR if all GitHub checks have passed, as well as the PR having the "ready-to-merge" label.

## Actual Behavior
One of our WIP PRs that didn't have an approval yet (which is one of the GitHub checks) and didn't have the "ready-to-merge" label was merged by Mergify: https://github.com/transcom/mymove/pull/7394

## Specifications

  - Pull Request URL: https://github.com/transcom/mymove/pull/7394
  - Mergify Config URL: https://github.com/transcom/mymove/blob/master/.mergify.yml
