### ISSUE TITLE
"Not with label" seems to be ignored

### ISSUE THREAD

**Issue by muhlemmer** [Mergifyio/mergify-engine#333]
This worked fine until today. We have set up mergify to merge after 1 review when the author is "trusted". However, certain PR's are more delicate and are not supposed to get merged untill 2 reviews are acquired. So we have the `review/need2` tag for that. This should disable the "Trused author" rule.

Mergify was properly holding some merges, until we resolved merge conflicts in two PRs today. There was 1 approving review and after Travis finished building, the PRs were merged regardless of label setting.

Pull requests are Mailu/Mailu#788 and Mailu/Mailu#799.

```
 pull_request_rules:
  - name: Successful travis and 2 approved reviews
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - label!=["status"/wip","status/blocked"]
      - "#approved-reviews-by>=2"
    actions:
      ....
  - name: Trusted author, successful travis and 1 approved review
    conditions:
      - author~=(kaiyou|muhlemmer|mildred|HorayNarea|adi90x|hoellen|ofthesun9)
      - status-success=continuous-integration/travis-ci/pr
      - label!=["status"/wip","status/blocked","review/need2"]
      - "#approved-reviews-by>=1"
    actions:
      ....
```
