### ISSUE TITLE
Always update pull requests to their target branch

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#421]
Some users would like to have their PR always update with the latest commits from the target branch.
As soon as something is merged in that branch, update the PR even if it's not mergeable according to pull request rules.

That could be a dedicated action.

**Comment by diba1013** [comment]
Just to provide our example for such an use-case. We want to always have Pull Request up to date with the corresponding base branch (e.g. master), so that the reviewer does not review code that is not part of the PR. For that, we provide the following config, ignoring draft PRs or PRs that have changes requested, i.e. are likely that the author needs to adapt the code and to update the branch. That is to avoid force overwriting the changes by either mergify or the author.

The same is done right before merging, but we do that with strict-merge (i.e. once approved).

Our current solution: https://github.com/retest/recheck-web/blob/master/.mergify.yml (we use a simplified Git-Flow):

```
- name: "rebase unreviewed non-release PRs"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "-draft"
    actions:
      rebase: {}
```

With this setup, it seems that mergify is somewhat lazy when updating a PR, once another PR has been merged into the same target branch. So I would assume that a condition `outdated` would be beneficial so that GitHub notifies mergify if a PR is outdated, and the corresponding action can be performed.

The question would be, what is the benefit of such a dedicated action vs rebase vs update? Such an "update" could be done multiple ways, depending on the workflow used in git. You could either rebase (which has its pros and cons) or merge the base branch into the PR. It would be great, if such an action is introduced, that the different to such approaches is specified and what the action does exactly.
