### ISSUE TITLE
Can't merge when "files" condition list is set

### ISSUE THREAD

**Issue by KEINOS** [Mergifyio/mergify-engine#430]
First of all, thank you for providing us such a great service!

I want to auto-merge the PR, only if the specified files in the root of the repo are changed. 

Such as "`/list1.json`" and/or "`/list2.json`". So I think I have to use the "files" condition in list format to do so.

```yaml
  conditions:
      - files=['list1.json', 'list2.json']
```

The below `.mergify.yml` works fine. It does the CircleCi test, merges, and deletes the branch.

```yaml
pull_request_rules:
  - name: automatic merge on CircleCI success
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
    actions:
      merge:
        method: merge
        strict: true
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
```

So, I add the `files` condition as below:

```yaml
pull_request_rules:
  - name: automatic merge on CircleCI success only if JSON changed
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=['list1.json', 'list2.json']
    actions:
      merge:
        method: merge
        strict: true
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
```

But as a result, only 1 rule (`delete_head_branch` action, `Rule: delete head branch after merge (delete_head_branch)`) matches and `merge` action does not.

Therefore it does nothing and the PR waits to merge manually. I tried changing one file and also changing both files but still the same.

**Comment by jd** [comment]
Your files syntax is not valid. The engine expects a string, so unless you have a file named `['list1.json', 'list2.json']`, it'll never work.

It should simply be `files=list1.json`.
We don't support `or` so you'd need another rule for `list2.json`.

**Comment by KEINOS** [comment]
@jd Thanks for the response!

> The engine expects a string, so unless you have a file named `['list1.json', 'list2.json']`, it'll never work.

Indeed.  I should've read the doc more carefully. The value type "`string`" was defined in the documents' [attribute list](https://doc.mergify.io/conditions.html#attribute-list) section.

<img width="691" alt="スクリーンショット 2019-06-10 22 59 23" src="https://user-images.githubusercontent.com/11840938/59200658-b0ad0480-8bd3-11e9-9cf3-53803207d1b2.png">

Since the description describes plurally and validating the `.mergify.yml` via `cURL` gave me "`The configuration is valid`" results, I mistakenly assumed that the value would be a string of a list. Doh.

> We don't support `or` so you'd need another rule for list2.json.

So, to be clear "`OR`" version and "`AND`" version would be like so?

- list1.json `OR` list2.json

```yaml
pull_request_rules:
  - name: automatic merge on CircleCI success if list1.json is changed
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=list1.json
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge on CircleCI success if list2.json is changed
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=list2.json
    actions:
      merge:
        method: merge
        strict: true
```

- list1.json `AND` list2.json

```yaml
pull_request_rules:
  - name: automatic merge on CircleCI success if list1.json is changed
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=list1.json
      - files=list2.json
    actions:
      merge:
        method: merge
        strict: true
```

I want to trigger auto-merge **ONLY IF** list1.json `OR` list2.json was changed and **no other files** such as the program code files are changed.

**Comment by jd** [comment]
You got this right, however, it won't exclude any other files. So what you want is:

```yaml
pull_request_rules:
  - name: automatic merge on CircleCI success if list1.json is changed
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=list1.json
      - "#files=1"
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge on CircleCI success if list2.json is changed
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=list2.json
      - "#files=1"
    actions:
      merge:
        method: merge
        strict: true

```

By checking that the number of modified file is 1, you're sure that no other file is modified.
