### ISSUE TITLE
Error !! Validate the configuration to get the summary

### ISSUE THREAD

**Issue by deepakvermacloud** [Mergifyio/mergify-engine#4349]
when i am going to validate my code with current pull request.  its showing Validate the configuration to get the summary . 
i am using simple code given by mergify simply. 

```
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
```
