### ISSUE TITLE
Not auto-merging PR after strict workflow merge commit

### ISSUE THREAD

**Issue by alecmocatta** [Mergifyio/mergify-engine#460]
1. PR from branch that's behind the base branch
2. Tests pass
3. Mergify pushes a merge commit to update to head of base branch
4. Tests pass
5. PR isn't merged?

See here https://github.com/alecmocatta/serde_pipe/pull/21.

```yml
  - name: automatic merge
    conditions:
      - base=master
      - status-success=tests
      - label!=work-in-progress
      - author=alecmocatta
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
```

I was expecting the PR to be merged by Mergify after the tests passed on the merge commit. What am I missing?
