### ISSUE TITLE
Assign Codeowner

### ISSUE THREAD

**Issue by NGL321** [Mergifyio/mergify-engine#464]
I would love a feature that automatically assigns the codeowner for edited files (as in the CODEOWNER file) to the PR.

Use case:
``` yml
pull_request_rules:
  - name: assign code owner
     conditions: []
     actions:
       assign:
         user: []
         codeowner: true
```
