### ISSUE TITLE
Add support for backport branch name regular expressions.

### ISSUE THREAD

**Issue by adamjstone** [Mergifyio/mergify-engine#494]
# Feature Request

We use Mergify's backport feature to [distribute trunk changes](https://github.com/RapidField/solid-instruments/blob/d1b8248c189b6459acbdbadd320456a023f920e3/.mergify.yml#L629) to feature branches (among other things). At present moment, we are editing our Mergify configuration each time we add or remove a feature branch, like so:

```yaml
- name: Backmerge from develop
  actions:
    backport:
      branches:
      - feature/abc
      - feature/xyz
```

## Desired behavior

The workflow for this use case would be dramatically simpler if Mergify was able to evaluate the branch name array using regular expressions, like so:

```yaml
- name: Backmerge from develop
  actions:
    backport:
      branches:
      - (^feature\/(.+)$)
```
