### ISSUE TITLE
Add rule templates

### ISSUE THREAD

**Issue by thislooksfun** [Mergifyio/mergify-engine#502]
Currently there is no way to share a list of conditions across multiple rules. This is a definitely missed opportunity as allowing this would make configuration much easier to write and maintain. My idea for how to implement this is as follows:

1. Define the top-level yml key `templates`, which is a dictionary
2. In the `templates` dict, you can define key-value pairs, each of which is a name and a list of rules.
3. When parsing rules, allow for the key `templates`, which is an array of strings, each of which is a key in the top-level `templates` dict
    2. When encountering the `templates` key, even recursively (see examples 1-3), it should recursively merge the keys into the rule.
    3. Namely, when encountering a dict key in the template (for example, the `actions` dict, it should perform a deep merge, preferring explicit rules over templated ones (example 1 below)
    4. When encountering an array (for example, the `conditions` array), the contents should be pre-pended, so explicit rules go to the end of the array (example 2 below)

### Example 1

```yml
templates:
  foo:
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: Some rule
    templates:
      - foo
    actions:
      merge:
        method: rebase
```
Should result in the merge method being `rebase`, **not** `merge`

### Example 2

```yml
templates:
  foo:
    conditions:
      - label=ready-to-merge

pull_request_rules:
  - name: Some rule
    templates:
      - foo
    conditions:
      - status-success=DeepScan
```
Should result in the conditions array being
```yml
- label=ready-to-merge
- status-success=DeepScan
```

### Example 3

```yml
templates:
  foo:
    templates:
      - bar
  bar:
    conditions:
      - label=ready-to-merge

pull_request_rules:
  - name: Some rule
    templates:
      - foo
    conditions:
      - status-success=DeepScan
```
Should still result in the conditions array being
```yml
- label=ready-to-merge
- status-success=DeepScan
```

### Full example

Before:
```yml
pull_request_rules:
  # Automatic Merging (humans)
  - name: Automatic merge for master when tagged and CI passes
    conditions:
      # Tagged ready
      - label=ready-to-merge

      # CI test success
      - status-success=unit-tests (10.x)
      - status-success=unit-tests (12.x)
      # Security check
      - status-success=DeepScan
      - status-success=security/snyk - package.json (thislooksfun)
      - "status-neutral=LGTM analysis: JavaScript"
      # Coverage check
      - status-success=codecov/patch
      - status-success=codecov/project
      # Not WIP
      - status-success=WIP
      # On master branch
      - base=master
    actions:
      merge:
        method: merge
        strict: true

  # Automatic Merging (bots)
  - name: Automatic merge for Greenkeeper pull requests
    conditions:
      # Was sent from Greenkeeper
      - author=greenkeeper[bot]
      - status-success=greenkeeper/verify

      # CI test success
      - status-success=unit-tests (10.x)
      - status-success=unit-tests (12.x)
      # Security check
      - status-success=DeepScan
      - status-success=security/snyk - package.json (thislooksfun)
      - "status-neutral=LGTM analysis: JavaScript"
      # Coverage check
      - status-success=codecov/patch
      - status-success=codecov/project
      # Not WIP
      - status-success=WIP
      # On master branch
      - base=master
    actions:
      merge:
        method: merge
        strict: true

  # Quality of life
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  - name: Remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}

  - name: Assign me
    conditions:
      - -author=greenkeeper[bot]
      - base=master
    actions:
      assign:
        users:
          - thislooksfun
```

After:
```yml
templates:
  common:
    templates:
      - ci
      - security
      - coverage
      - wip
      - base-master
    actions:
      merge:
        method: merge
        strict: true
  tagged:
    conditions:
      # Tagged ready
      - label=ready-to-merge
  ci:
    conditions:
      # CI test success
      - status-success=unit-tests (10.x)
      - status-success=unit-tests (12.x)
  security:
    conditions:
      # Security check
      - status-success=DeepScan
      - status-success=security/snyk - package.json (thislooksfun)
      - "status-neutral=LGTM analysis: JavaScript"
  coverage:
    conditions:
      # Coverage check
      - status-success=codecov/patch
      - status-success=codecov/project
  wip:
    conditions:
      # Not WIP
      - status-success=WIP
  base-master:
    conditions:
      # On master branch
      - base=master
  greenkeeper:
    conditions:
      # Was sent from Greenkeeper
      - author=greenkeeper[bot]
      - status-success=greenkeeper/verify
      

pull_request_rules:
  # Automatic Merging (humans)
  - name: Automatic merge for master when tagged and CI passes
    templates:
      - common
      - tagged

  # Automatic Merging (bots)
  - name: Automatic merge for Greenkeeper pull requests
    templates:
      - common
      - greenkeeper

  # Quality of life
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  - name: Remove outdated reviews
    templates:
      - base-master
    actions:
      dismiss_reviews: {}

  - name: Assign me
    templates:
      - base-master
    conditions:
      - -author=greenkeeper[bot]
    actions:
      assign:
        users:
          - thislooksfun
```
