### ISSUE TITLE
`commit_message_template` does not have access to the `labels` list

### ISSUE THREAD

**Issue by mkatychev** [Mergifyio/mergify-engine#5107]
https://docs.mergify.com/workflow/actions/copy/ the `labels` attribute is not available to `commit_message_template`:
> `labels`
> 
> list of string
> 
> The list of labels to add to the created pull requests.

```yaml
actions:
  queue:
    name: default
    method: squash
    allow_merging_configuration_change: true
    commit_message_template: |
      {{ title }} (#{{ number }})

      Approved by: @{{ approved_reviews_by | join(', @') }}

      Labels: {{ labels | join(',') }}

      {{ body }}
```

This is less of a bug and more of a feature request to have `labels` GH data exposed in the same way as `approved_reviews_by` is.
