### ISSUE TITLE
`request_reviews` triggers in excess for a team when a member of the team approves a pull request

### ISSUE THREAD

**Issue by mkatychev** [Mergifyio/mergify-engine#5109]
## Expected Behavior
If a member of an team responds or appros so that the review request of said team is dropped, the request review form team does not get reapplied

## Actual Behavior

<img width="1015" alt="image" src="https://github.com/Mergifyio/mergify/assets/11223234/08ad4a37-4147-4056-80f7-e6006568bad3">

## Steps to Reproduce the Problem

1. have a PR that meets the above conditions
2. PR is approved by a member of the team(s) under actions

## Specifications

  - Pull Request URL: private
  - Mergify Config URL: minimal example below
  
```yaml
# .mergify/config.yml
pull_request_rules:
  - name: add infra to PRs that touch deployment files
    # https://docs.mergify.com/conditions/#how-to-match-lists
    conditions:
      - label=infra
      - -draft
      - -closed
      - base=main
    actions:
      request_reviews:
        teams:
          - "@team/infra"
```

**Comment by DouglasBlackwood** [comment]
Hi!

Mergify will request the review until the conditions are met. To avoid requesting indefinitely, you could add `-approved-reviews-by=@team/infra` in the conditions, so Mergify will request the review only if `@team/infra` didn't approve.

```yaml
# .mergify/config.yml
pull_request_rules:
  - name: add infra to PRs that touch deployment files
    # https://docs.mergify.com/conditions/#how-to-match-lists
    conditions:
      - label=infra
      - -draft
      - -closed
      - base=main
      - -approved-reviews-by=@team/infra
    actions:
      request_reviews:
        teams:
          - "@team/infra"
```
