### ISSUE TITLE
Handle ci/circleci tests with a space in the name

### ISSUE THREAD

**Issue by patrickviet** [Mergifyio/mergify-engine#5116]
## Expected Behavior

No syntax error - when using as a check `- check-success=ci/circleci: test`

As per https://docs.mergify.com/integrations/circleci/
And also as per supposedly repaired on https://github.com/Mergifyio/mergify/issues/233

## Actual Behavior

<img width="1162" alt="Screen Shot 2024-06-25 at 1 59 26 PM" src="https://github.com/Mergifyio/mergify/assets/2391018/07f755ca-2e95-411e-b284-248cf0f6bbc0">

```
The current Mergify configuration is invalid
Extra inputs are not permitted @ pull_request_rules → item 0 → conditions → item 1 → check-success=ci/circleci → test
Field required @ pull_request_rules → item 0 → conditions → item 1 → and
Field required @ pull_request_rules → item 0 → conditions → item 1 → or
Field required @ pull_request_rules → item 0 → conditions → item 1 → not
```

## Steps to Reproduce the Problem

use this config file in a branch

```
pull_request_rules:
  - name: automatic merge
    conditions:
    - label=automerge
    - check-success=ci/circleci: test
    actions:
      queue:
        name: speculative

queue_rules:
  - name: speculative
    queue_conditions:
    - check-success=ci/circleci: test
    speculative_checks: 3
```

Also doesn't work with `check-success="ci/circleci: test"`
