### ISSUE TITLE
Show warning if assignee is trying to merge a PR without reviews

### ISSUE THREAD

**Issue by HaruChebrolu** [Mergifyio/mergify-engine#5126]
## Expected Behavior
PR shouldn't be merged when PR has no reviews or if assignee is trying to merge it.

## Actual Behavior
PR was getting merged

## Steps to Reproduce the Problem

  1. We have below configuration in mergify.yaml
```
  ---
pull_request_rules:
  - name: automatic merge
    conditions:
      - label!=DNM
      - label!=work-in-progress
      - base=master
      - "approved-reviews-by=@red-hat-storage/cephci-top-level-reviewers"
      - "check-success=tox (3.9.18)"
      - check-success=WIP
    actions:
      merge:
        method: merge
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: >
          "This pull request now has conflicts with the target branch.
          Could you please resolve conflicts and force push the corrected
          changes?"
```
  2. So anyone can have a label `approved` in labels, so its getting merged.
  3. Can we have a condition in above configuration file in such a way only when reviewers keep label as `approved`, PR should get merged.

## Specifications

  - Pull Request URL:
  - Mergify Config URL:

**Comment by jd** [comment]
Hi @HaruChebrolu,

There are no label conditions in your configuration above. I imagine you want to add one? In that case you'd need:

```yaml
pull_request_rules:
  - name: automatic merge
    conditions:
      - label!=DNM
      - label!=work-in-progress
      - label = approved
      - base=master
      - "approved-reviews-by=@red-hat-storage/cephci-top-level-reviewers"
      - "check-success=tox (3.9.18)"
      - check-success=WIP
    actions:
      merge:
        method: merge
```
This means the label `approved` will be required to merge the PR.
