### ISSUE TITLE
New bug: automatic rebases cause `pull request manually updated` and dequeuing

### ISSUE THREAD

**Issue by Rowan-Mather** [Mergifyio/mergify-engine#5135]
![Image](https://github.com/user-attachments/assets/5a732a73-9658-434d-9703-a0078c751c6c)

I have a bot account responsible for automatic rebases configured in the .mergify.yml as such:
```
queue_rules:
  - name: default
    update_method: rebase
    merge_method: merge
    update_bot_account: my-bot-account
```
I also have some required github status checks which run when the branch is pushed to.

As you can see in the attached image, after an automatic rebase mergify has started complaining of the pull request being manually updated and dequeuing it. This does not occur if the branch does not need to be rebased.

The changelog lists ['Autosquash disabled by default'](https://changelog.mergify.com/changelog/autosquash-disabled-by-default). I strongly suspect my issue has been caused by this change, since it is related to the pull request author, and I noticed these messages appearing on 17/3/2025 (the next working day after the change).
