### ISSUE TITLE
'Page build failed' error after auto merging pull request to master branch

### ISSUE THREAD

**Issue by K-Maehashi** [Mergifyio/mergify-engine#617]
I'm using GitHub-Pages with an organization account. Mergify successfully merge my branch into `master`, but building GitHub-pages always fails. I need to recompile pages manually.

Interestingly, if I use my personal account, I can build GitHub-Pages.

**Comment by jd** [comment]
Hi!

Thanks for reporting this. We'd need more details to be able to debug this. Can you provide a pull request URL that triggered this behavior?

If you noticed that on a private repository, feel free to contact support@mergify.io and we'll check it out.

**Comment by K-Maehashi** [comment]
@jd Thanks a lot. Actually, I need to close the repo for now because we're still in testing stage.
The situation we're in is exactly same as these issues: https://github.com/vmware/precaution/issues/205#issuecomment-487937613
So probably it's the issue on GitHub side?

**Comment by K-Maehashi** [comment]
Maybe this is not the best way to solve it, but I found we can use GitHub Action. Something like this:
```
name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dir
        env:
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
```
