### ISSUE TITLE
Support for "array of string" in `approved-reviews-by`

### ISSUE THREAD

**Issue by SteVwonder** [Mergifyio/mergify-engine#656]
In this PR (https://github.com/flux-framework/docs/pull/9), I am trying to have multiple usernames/teams that can approve PRs for mergify.  Based on [this documentation](https://doc.mergify.io/conditions.html#attribute-list), it says the `approved-reviews-by` can be an "array of string".  I can't seem to get that to work.  Both `- approved-reviews-by=[@flux-framework/core,@flux-framework/docs]` and

```yaml
- approved-reviews-by=
  - @flux-framework/core 
  - @flux-framework/docs
```

are rejected.

After poking around in the rules parser, [this line](https://github.com/Mergifyio/mergify-engine/blob/4d8f774d801355eb5aca6a8791d3b16367cdfab8/mergify_engine/rules/parser.py#L21) makes it look like that config option only supports a single username/team.  Is that right?

**Comment by jd** [comment]
The documentation says it *is* an array of string.
There's no `or` operator in the conditions, so you'd need to duplicate your rules, but you can do something like:


```
pull_request_rules:
  - name: merge for team docs
    conditions:
       - approved-reviews-by=@flux-framework/docs
    actions:
       merge:
          method: merge

  - name: merge for team core
    conditions:
       - approved-reviews-by=@flux-framework/core
    actions:
       merge:
          method: merge
```
