### ISSUE TITLE
Allow to rebase+merge with --no-ff

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#67]
Feature requested from https://github.com/isaacs/github/issues/1135 and https://github.com/isaacs/github/issues/1143

**Comment by garyverhaegen-da** [comment]
Can't you do that with the existing actions? From my understanding of the documentation,

```
- method: merge
  strict: true
  strict_method: rebase
```

should give you the semi-linear history, at least if `method: merge` is equivalent to pressing the merge button on GitHub (which includes `--no-ff`), and

```
- method: rebase
  strict: true
  strict_method: rebase
```

should give you the linear version (i.e. `--ff-only`) if it matches pressing the "rebase" button on GitHub.

**Comment by ljharb** [comment]
Why isn’t this planned? It’s a core git feature that GitHub doesn’t offer.

**Comment by jd** [comment]
Both workflows are achievable today through the merge queue, but not via the merge action.

The key is configuring single-PR inplace checks (`max_parallel_checks: 1`, `batch_size: 1`) with the right update and merge methods.

Linear history (`--ff-only`):

```
queue_rules:
  - name: default
    batch_size: 1
    merge_method: rebase
    update_method: rebase

merge_queue:
  max_parallel_checks: 1
```

The queue rebases each PR on top of main, runs CI on it in-place, then rebase-merges it — giving you a clean linear history with no merge commits.

Semi-linear history (`--no-ff`):

```
queue_rules:
  - name: default
    batch_size: 1
    merge_method: merge
    update_method: rebase

merge_queue:
  max_parallel_checks: 1
```

Same idea, but using a merge commit at the end — you get rebased commits wrapped in a merge commit, which is the semi-linear history `--no-ff` provides.

Both guarantee every commit on main has passed CI against the actual branch state at merge time. That said, we don't have plans to go further than this on merge strategy options at this point.

**Comment by ljharb** [comment]
The merge queue is a nonstarter since it uses rebasemerge or squashmerge. The issue is requesting specifically _the merge action_.

The intention is not a semi-linear history, it's an _actually_ linear history - where even the PR ref sits on the line.

**Comment by jd** [comment]
So that's something we have no intention to support indeed.

**Comment by ljharb** [comment]
That’s surprising :-/ can you elaborate on why not?

**Comment by jd** [comment]
Actually, we might support this IIUC: the merge queue has a fast-forward merge method that does exactly what you're describing. It updates the base branch ref directly to the PR's head SHA via the Git API, so the PR commits end up on main with identical SHAs. No commit recreation.

```
queue_rules:
  - name: default
    batch_size: 1
    merge_method: fast-forward
    update_method: rebase

merge_queue:
  max_parallel_checks: 1
```

This rebases the PR onto main, runs CI, then fast-forwards main to the PR tip. Linear history, PR ref on the line.

It does require the merge queue (not the merge action), but that's because fast-forward only works if the branch is guaranteed to be up-to-date, which is what the queue ensures. But there's no plan to add this to the merge action.
