### ISSUE TITLE
Merged PR with label conditions do not always result in the same action

### ISSUE THREAD

**Issue by 0xc0170** [Mergifyio/mergify-engine#699]
An example can be found here: https://github.com/ARMmbed/mbed-os/pull/12291

This is the rule:

```
  # Check if version label is applied
  - name: release version is a must for merged PRs
    conditions:
      - merged
      - -label~=^(release-version)
    actions:
      label:
        add: ['Release review required']
      comment:
        message: This PR does not contain release version label after merging.

```
I checked this in simulator and also on Github. The rule looks fine to me. But somehow we get the comment and label add for PRs that do not satisfy this rule. Only some PRs are affected.
What I suspect, if the label "release-version: xxx" is added after PR is being merged, might play a role here. It should not however.
