### ISSUE TITLE
Backport label keeps CI from going green

### ISSUE THREAD

**Issue by martijnbastiaan** [Mergifyio/mergify-engine#789]
Over at https://github.com/clash-lang/clash-compiler we use mergify to backport PRs to stable branches. We're generally happy with how this works :), but the mergify bot currently keeps our CI from going green. 

Steps to reproduce:

1. Setup backporting. We use:

```
pull_request_rules:
  - name: backport patches to 1.2
    conditions:
      - base=master
      - label=backport 1.2
    actions:
      backport:
        ignore_conflicts: True
        branches:
          - "1.2"
```

2. Open a PR, label `backport 1.2`
3. Wait until CI is finished and observe:

![Selection_028](https://user-images.githubusercontent.com/5658854/76318378-e6efef80-62dd-11ea-8522-377d3402f873.png)

![Selection_029](https://user-images.githubusercontent.com/5658854/76318416-f5d6a200-62dd-11ea-9759-59aad5c24a75.png)

At a glance it seems like the CI is still processing the PR, but it turns out it's mergify instead. i couldn't find a related settings in the docs, nor an open issue. Is there a way of "fixing" this behavior? If not, what would it take to fix this issue?
