### ISSUE TITLE
auto addon reviewers - cond. not recognise team

### ISSUE THREAD

**Issue by Borda** [Mergifyio/mergify-engine#876]
We are facing an issue hot to recognise a team in `review-requested!=core-contributors`

Our situation is that have a rule that PR can be merged after 3 approvals, to do so we assign the review to a group `core-contributors` but Github allows to have the ethe group just once and we a member of this group does review it adds his approval and removes a team from request... So we want to make a simple rule if the number of approvals is lower then required and the team is not among requested, add the ream...

I have drafted this but it does not recognise the lean in condition
```
  - name: add core reviewer
    conditions:
      # number of review approvals
      - "#approved-reviews-by<3"
      # team is not requested yet
      - review-requested!=@PyTorchLightning/core-contributors
    actions:
      request_reviews:
        teams:
          - "@PyTorchLightning/core-contributors"
```

**Comment by sileht** [comment]
it's should be just `review-requested!=@core-contributors`

**Comment by sileht** [comment]
You don't need to filter out `review-requested`, Mergify have this protection built-in. The configuration your need is just:

```
  - name: add core reviewer
    conditions:
      - "#approved-reviews-by<3"
    actions:
      request_reviews:
        teams:
          - core-contributors
```

We use the same here https://github.com/Mergifyio/mergify-engine/blob/master/.mergify.yml#L60-L67
