### ISSUE TITLE
Feature Request: Action to change base

### ISSUE THREAD

**Issue by azai91** [Mergifyio/mergify-engine#918]
Love the product so far.  Was wondering if there was an action to update the base branch that a pull request is compared to? If not, I think that would be a great feature to add. Something along the lines of:

```
pull_request_rules:
  - name: Change base
    conditions:
      - "title~=^\\[Release\\].+"
    actions:
      chnange_base:
        branch: release
```
